### ISSUE TITLE
Creation of rrd files fails when graph_data_size got customized

### ISSUE THREAD

**Issue by damon1991** [munin-monitoring/munin#1191]
**Describe the bug**
When setting any custom value for graph_data_size (e.g.: graph_data_size custom 1d, 1m for 1w, 5m for 1t, 15m for 1y) munin is not able to create the rrd files.
The following error gets logged:
[ERROR] Unable to create '/var/lib/munin/foo.example.com-interrupts-intr-d.rrd': Invalid step 0: value must be positive

**To Reproduce**
1. Go to munin configuration file and set a custom value for graph_data_size
2. Delete all rrd files if any are already existing
3. Wait for munin update to run.
4. Error should get logged in munin-update.log

**Expected behavior**
Even with customized graph-data size the initial file should get created.

**Desktop (please complete the following information):**
 - Ubuntu 18.04
 - Munin Version 2.0.37

**Additional context**
After removing the custom graph-data-size the next update job created all missing files.
Entering the custom graph-data-size after the files got created is working as expected.

**Comment by steveschnepp** [comment]
> `Invalid step 0`
This is due to the fact that you asked for a granularity too small compared to the `update_rate`. 

Here it is `1m` compared to the `5m` `update_rate`. Therefore you ask for a less-than-one multiplier (which is integer, therefore 0)

This has been fixed in 2.999.x in 826d81b4ac4fba0141313437d68cf57eda9bb664.
