### ISSUE TITLE
munin-node fails to start on a Debian Buster LXC container (namespacing)

### ISSUE THREAD

**Issue by tomlaredo** [munin-monitoring/munin#1278]
**Describe the bug**

munin-node package doesn't start (causing install to fail) on an LXC container (running Debian Buster / 10 with systemd) due to mount namespacing.
The current workaround is to enable nesting feature, which presents a security risk as /proc and /sys on th host is accessible from the guest.

**To Reproduce**
```
# apt install munin-node
[...]
Restarting munin-node..Job for munin-node.service failed because the control process exited with error code.
See "systemctl status munin-node.service" and "journalctl -xe" for details.
invoke-rc.d: initscript munin-node, action "start" failed.
● munin-node.service - Munin Node
   Loaded: loaded (/lib/systemd/system/munin-node.service; disabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2020-02-06 14:08:23 UTC; 5ms ago
     Docs: man:munin-node(1)
           http://munin.readthedocs.org/en/stable-2.0/reference/munin-node.html
  Process: 3777 ExecStart=/usr/sbin/munin-node $DAEMON_ARGS (code=exited, status=226/NAMESPACE) ==========> Here is the important info
dpkg: erreur de traitement du paquet munin-node (--configure) :
installed munin-node package post-installation script subprocess returned error exit status 1
Traitement des actions différées (« triggers ») pour man-db (2.8.5-2) ...
Traitement des actions différées (« triggers ») pour systemd (241-7~deb10u2) ...
Des erreurs ont été rencontrées pendant l'exécution :
munin-node
[...]
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
```
# dpkg -l | grep munin-node
iF  munin-node                     2.0.49-1                      all          network-wide graphing framework (node)
```
```
# tail -n 100 /var/log/syslog
Feb  6 16:06:10 vs-mail systemd[1]: Starting Munin Node...
Feb  6 16:06:10 vs-mail systemd[3095]: munin-node.service: Failed to set up mount namespacing: Permission denied
Feb  6 16:06:10 vs-mail systemd[3095]: munin-node.service: Failed at step NAMESPACE spawning /usr/sbin/munin-node: Permission denied
Feb  6 16:06:10 vs-mail systemd[1]: munin-node.service: Control process exited, code=exited, status=226/NAMESPACE
Feb  6 16:06:10 vs-mail systemd[1]: munin-node.service: Failed with result 'exit-code'.
Feb  6 16:06:10 vs-mail systemd[1]: Failed to start Munin Node.
Feb  6 16:06:10 vs-mail systemd[1]: munin-node.service: Service RestartSec=100ms expired, scheduling restart.
Feb  6 16:06:10 vs-mail systemd[1]: munin-node.service: Scheduled restart job, restart counter is at 1.
Feb  6 16:06:10 vs-mail systemd[1]: Stopped Munin Node.
```

**Additional context**
Host: Debian Buster 10.2 running latest Proxmox 6
Guest : Debian Buster 10.2 (LXC container)
munin-node 2.0.49-1
systemd 241-7~deb10u2

**Comment by sumpfralle** [comment]
Maybe it is sufficient to override certain hardening flags of the `munin-node.service` before starting it? (via `systemctl edit munin-node`)

The following hardening flags could be at fault:
```
[Service]
PrivateDevices=false
PrivateTmp=true
ProtectHome=true
ProtectSystem=full
```

I do not know too much about LXC and such namespace issues. Thus it would be helpful, if you could determine, which specific setting causes the issue for you.

I guess, this is a problem specific to LXC and systemd services (not limited to `munin-node`). Thus I can imagine, that other people already found suitable solutions for this kind of problems.

**Comment by sumpfralle** [comment]
@tomlaredo: ping?

**Comment by YohannLYD** [comment]
> The following hardening flags could be at fault:
> 
> ```
> [Service]
> PrivateDevices=false
> PrivateTmp=true
> ProtectHome=true
> ProtectSystem=full
> ```

Hi all,
I encountered the exact same issue as @tomlaredo regarding the LXC containers running Debian Buster (Proxmox 6 host).
@sumpfralle, I edited the munin-node.service conf file as you suggested by setting all the values you mentionned to false which solved the issue. munin-node could start again on the container.

I have sincerely no idea what are the security implications by doing so but the solution suits me better this way than enabling the nesting feature.

```
[Service]
PrivateDevices=false
PrivateTmp=false
ProtectHome=false
ProtectSystem=false
```

**Comment by sumpfralle** [comment]
Interesting!

It would be good to know, which is the minimum set of overrides that would work for you. Then I could add this to the documentation.

Regarding the lxc containers: I guess, these are stored below `/var/lib/lxc`? In this case I would assume, that `ProtectSystem=false` is sufficient?

(at the moment I just wild guessing here, too)

**Comment by YohannLYD** [comment]
The config settings are indeed stored in `/var/lib/lxc` but the root filesystem can be located on other volumes, which is my case.

I have to set all the aforementioned options to false for the service to run. Setting only `ProtectSystem=false` is not enough.

**Comment by sumpfralle** [comment]
Thanks for checking the minimum set of capabilities!

After reading again the first sentence of the original poster ...:
> munin-node package doesn't start (causing install to fail) on an LXC container (running Debian Buster / 10 with systemd) due to mount namespacing.

... I understand, that the dockerized system simply lacks the `CAP_SYS_ADMIN` capability (see [recommended properties of a container suitable for systemd](https://systemd.io/CONTAINER_INTERFACE/#what-you-shouldnt-do)).

I do not know too much about docker and its recommended modes of operations, but I see the following points that may be worth a discussion:
* A) running an interactive shell in a docker container is probably useful for exploring and experimentation, but not for running services. I understand docker to be a *service container*, not a sandbox for generic interactive operations. Probably a typical docker file would just specify all packages to be installed and the exact commands to be executed in order to run the wanted service. The *service* file should not be used here, I guess.
* B) Is there really systemd running in the docker system? Are you sure, that this is necessary? I would assume, that systemd (due to the requirement for `CAP_SYS_ADMIN`) should be run only in the host system (and probably manage the dockerized applications from the outside).
* C) Running the docker system in privileged mode in order to allow `munin-node` to drop some of these privileges (via the hardening flags specified in its systemd service definition) sounds like an approach that *reduces* the isolation of the environment.

Thus I assume, that you should not try to use the systemd service files *inside* a docker container. Thus I do not see the need for a change in munin.

If anyone is more familiar with common practices around docker deployments: please correct me.

**Comment by YohannLYD** [comment]
Just to be specific, the original poster and I are not using docker as the containerization method but LXC.
The principle may be similar but the deployment/usage is different in my opinion.

It's worth saying that those namespace issues within LXC containers started appearing since the upgrade to Debian Buster. There are very similar issues that occur when trying to install `redis-server` on a LXC running Debian 10.

So I think this has something to do with systemd's update which I confirm is running in the LXC container.

> Thus I assume, that you should not try to use the systemd service files inside a docker container. Thus I do not see the need for a change in munin.

I don't think this is the right way to solve things, I am used to deploy my services on Debian based LXC containers. I don't really want to run a full VM just for a single service and running it on the virtualization host is not an option either.

There has been a lot of mess around systemd being set as the default service manager on Debian. I am not knowledgeable at all about it but I suppose we are experiencing of the reason it's criticized...

I am going to stick to the solution you first mentioned (hardening flags) as this is an acceptable workaround for me for the moment.

**Comment by sumpfralle** [comment]
> Just to be specific, the original poster and I are not using docker as the containerization method but LXC.
> The principle may be similar but the deployment/usage is different in my opinion.

What a shame - I completely went off track :(

Yes, indeed - this is completely different and I take back almost everything I said above. Let us start again ...

> I don't think this is the right way to solve things, I am used to deploy my services on Debian based LXC containers. I don't really want to run a full VM just for a single service and running it on the virtualization host is not an option either.

For docker I would stick to my previous argument.

For LXC your approach is obviously the right one: it should just work as expected - I agree.

I am quite confident, that this is not a munin-specific issue, since it surely affects almost every other systemd service file out there, too.

Digging around I stumbled upon the following details that may lead into the right direction:
* [debian#918839](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918839): Backports 3 patches from lxc 3.1 to have Apparmor confinement working properly with systemd 240.
    * Maybe you are using an older version of linux, lxc or systemd?
* [systemd#6876](https://github.com/systemd/systemd/pull/6876#issuecomment-331929226): settings like `ProtectSystem` are supposed to be ignored, if they cannot be enforced.
    * I am not sure, why this fails to work in your case.
* [blog article](https://blog.iwakd.de/lxc-cap_sys_admin-jessie): the article explains, that security settings for services need to be disabled manually in case of a lacking `CAP_SYS_ADMIN` (see the end of the article around *Dealing with services that use these features*).
    * But this article is almost five years old, so I am quite sure, that this can be done better, today.

Maybe you could verify, whether one of the above is applicable to your situation?

**Comment by tomlaredo** [comment]
Hi everyone, sorry for the long time I took to respond.

I'm using the latest systemd version for Debian Buster (241) and I was still having the issue before overring the systemd service specific configuration.

From my side, I found this particular working set (put this into /etc/systemd/system/munin-node.service.d/override.conf after having created the corresponding directory):
```
[Service]
PrivateTmp=false
ProtectHome=false
ProtectSystem=false
```

`PrivateDevices=false` seems to be unnecessary.
Don"t forget to systemctl daemon-relaod and then service munin-node restart after that.

> I am quite confident, that this is not a munin-specific issue, since it surely affects almost every other systemd service file out there, too.

I had this issue with several services (munin-node, apache2, varnish/varnishncsa, logrotate, mysql...). I'm not completely sure what should be changed here (systemd / LXC's Apparmor profiles / munin-node) but something should be done from one side or another to ensure services can start/install without failing.

**Comment by sumpfralle** [comment]
As far as I understand the issue, the following hint from the Debian package maintainer of LXC should solve the issue:

> AppArmor support in Debian has increased, thus preventing some systemd
> isolation features to work in LXC 3.0.X. Debian has backported some
> patches from LXC 3.1 that, along with some configurations in a
> container, will allow systemd isolation features to work.
>
> The required configuration parameters are the ones which follow:
>    lxc.apparmor.profile = generated
>    lxc.apparmor.allow_nesting = 1
>
> These parameters are provided in the `/etc/lxc/default.conf` file
> shipped with LXC 3. Hence, any newly created container will have these
> parameters set properly, execpt if you alter the forementionned file.

See [Debian#920643](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=920643#34)

Thus everyone stumbling upon this issue should check:
* whether the content of `/etc/lxc/default.conf` follows the above default
* whether the problematic container actually uses this setting (containers created before this change will use the previous setting)

I think, this should solve the issue. If this is not the case: please comment and/or re-open this issue.
