### ISSUE TITLE
munin-limits: [WARNING] Missing configuration options for contact no; skipping

### ISSUE THREAD

**Issue by mf69** [munin-monitoring/munin#1308]
Using "contacts no" in munin.conf seems to surface this in the munin-limits.log

```[WARNING] Missing configuration options for contact no; skipping```

I **think** I've traced this down to a bad match for "none" vs. "no" in this section of LimitsOLD.pm
https://github.com/munin-monitoring/munin/blob/master/lib/Munin/Master/LimitsOld.pm
(Lines 682-689)
```
682    foreach my $c (split(/\s+/, $contactlist)) {
683       next if $c eq "none"; <=========
684        my $contactobj = munin_get_node($config, ["contact", $c]);
685        if(!defined $contactobj) {
686            WARN("[WARNING] Missing configuration options for contact $c; skipping");
687            next;
...
```

The documentation I've found does not mention 'contacts none'.

**Comment by sumpfralle** [comment]
Good catch!

Indeed there is a difference between implementation and documentation.

I tend to adjust the documentation (change `no` to `none`), since everyone who stumbled upon the issue was surely hit by the same log messages that you discovered surely worked around it by using `none`. These users would suffer from a change of the code.

Additionally `none` sounds like a more reasonable value for `contacts`, than `no`.

@steveschnepp: do you have an opinion?

**Comment by steveschnepp** [comment]
Documentation fixes are always preferred, if sensible.

As, I tend to agree with Linus in the way "don't brake a user's workflow" when there's no super strong reason.

**Comment by HerroBert** [comment]
And how about that?
http://guide.munin-monitoring.org/en/latest/reference/munin.conf.html
