### ISSUE TITLE
munin-run doesn't work on RHEL 8.2

### ISSUE THREAD

**Issue by kimheino** [munin-monitoring/munin#1340]
For original bug report see:

https://bugzilla.redhat.com/show_bug.cgi?id=1852345

Copy-paste of above bug:

Description of problem:

Munin-run does not work after updating to CentOS-8.2

Version-Release number of selected component (if applicable):
munin-node-2.0.54-2.el8.noarch

How reproducible:
# munin-run cpu

Actual results:
# munin-run cpu
Unknown assignment: LockPersonality=no

Additional info:
It works by adding the --ignore-systemd-properties option

# munin-run cpu --ignore-systemd-properties
user.value 74129
nice.value 59603
system.value 333661
idle.value 220220704
iowait.value 17561
irq.value 472283
softirq.value 179918
steal.value 0
guest.value 0

**Comment by sumpfralle** [comment]
We discussed this in the IRC channel (`#munin` at `irc.oftc.net`).

RHEL seems to have backported certain systemd features into v239 (specifically `RestrictSUIDSGID` and `LockPersonality`), but these backports seem to be only partial. Thus `munin-run` fails. We came to the conclusion, that `munin-run` will skip applying systemd's restrictions for `munin-run`. @kimheino will patch the packaging accordingly.

Closing this issue, since it is distribution-specific.
