### ISSUE TITLE
cpuspeed graph breaks after plotting a few values

### ISSUE THREAD

**Issue by dotmpe** [munin-monitoring/munin#1384]
I have a mostly blank cpuspeed graph with only a few scribbles. In the log I find:
```
2021/02/17 03:50:05 [ERROR] In RRD: Error updating /var/lib/munin/opi/opi-cpuspeed-cpu3-d.rrd: /var/lib/munin/opi/opi-cpuspeed-cpu3-d.rrd: not a simple signed integer: '19469700000.0000'
```

To check I fetch values manually:
```
> telnet localhost 4949
fetch cpuspeed
cpu0.value 1.95254e+10
cpu1.value 1.95254e+10
cpu2.value 1.95254e+10
cpu3.value 1.95254e+10
.
```
Munin reads the scientific notation correctly but turns it into a float? Then why does it plot a few values.

OS: Armbian Focal (Ubuntu 20.04.2) Linux 5.10.16-sunxi armv7l
Munin node version: 2.0.56-1ubuntu1

**Additional info**
The source code is the awk invocation here:
https://github.com/munin-monitoring/munin/blob/ace9a23aa14a314828b4b8a34b8db3bbea3168ee/plugins/node.d.linux/cpuspeed.in#L147

The format that awk uses for integers can be set by adding ``BEGIN {OFMT = "%.0f"}``
https://fordodone.com/2013/05/27/printing-large-integers-with-awk/

```
value=$(awk 'BEGIN {OFMT = "%.0f"} { cycles += $1 * $2 } END { print(cycles / 100); }' "$c/cpufreq/stats/time_in_state") 
```

Result: the cpuspeed graph starts to plot again.

**Comment by sumpfralle** [comment]
Thank you for your report!

> Munin reads the scientific notation correctly but turns it into a float? Then why does it plot a few values.

The problem here is, that (depending on the existence of `/sys/devices/system/cpu/cpu0/cpufreq/stats/time_in_state`) the datatype `GAUGE` or `DERIVE` is used in this plugin. For `DERIVE` only integer values are allowed. Thus rrdtool complains about the floats.

This specific problem was fixed (similar to your suggestion) in 84a89195c3ac953b144d2c743d7a9de4583e3c10 (Munin 2.0.58).
