### ISSUE TITLE
[plugins/apt_all] Use of uninitialized value $ENV{"MUNIN_PLUGSTATE"} in concatenation (.) or string at /usr/share/munin/plugins/apt_all line 110.

### ISSUE THREAD

**Issue by ruliane** [munin-monitoring/munin#1393]
**Describe the bug**
When executing the newest version of `apt_all`:
```
Use of uninitialized value $ENV{"MUNIN_PLUGSTATE"} in concatenation (.) or string at /usr/share/munin/plugins/apt_all line 110.
pending_buster_updates.value 0
hold_buster_updates.value 0
pending_buster.value 0
hold_buster.value 0
```
(Note the warning is written to STDERR.)

**To Reproduce**
`# /usr/share/munin/plugins/apt_all`

**Expected behavior**
No error expected.

**Desktop (please complete the following information):**
 - Debian Buster w/ plugin [apt_all](https://github.com/munin-monitoring/munin/blob/master/plugins/node.d.linux/apt_all) from commit https://github.com/munin-monitoring/munin/commit/cd28c42425dd6a89a7017419c1489fd6f0413c41
 - Munin Version 2.0.49 (except `apt_all` plugin)

**Additional context**
I replaced the original plugin after running into issue https://github.com/munin-monitoring/munin/issues/1358.

**Comment by ruliane** [comment]
The offending line was issued on https://github.com/munin-monitoring/munin/commit/904a84e392ed2b86ba82c553ec84527b1a31127b#diff-f38166d0e111b916a4b0263dd15076a3a05600b6a8a9407a9ad8ae2997e0e4b3R42

There may be a good reason not to reuse the previous line which was:
`    my $statefile = ($ENV{MUNIN_PLUGSTATE} || '/var/lib/munin-node/plugin-state/nobody/') . "/plugin-apt.state";`

Should we roll back this line ?

**Comment by sumpfralle** [comment]
Thank you for your report!

In general munin plugins are not supposed to be executed directly.
Instead you should use `munin-run` - this will provide the relevant environment variables and other details.
Thus the above warning is to be expected. We could hide it, but this would just obscure the fact, that you are doing something, that you should not do :)

In this specific case you may be tempted to call the plugin directly, since it supported an `update` argument (for calling `apt-get update`). This is still possible for the plugin in the `stable-2.0` branch, which you should use until munin v3 (`master`) is released.
I just clarified this detail in the documentation for the plugin in the `master` branch: #1394

If you want to update the `apt_all` plugin, then I would recommend to install the munin packages in the Debian backports repository for Buster. They are based on the `stable-2.0` branch.

**Comment by ruliane** [comment]
> 
> 
> Thank you for your report!
> 
> In general munin plugins are not supposed to be executed directly.
> Instead you should use `munin-run` - this will provide the relevant environment variables and other details.
> Thus the above warning is to be expected. We could hide it, but this would just obscure the fact, that you are doing something, that you should not do :)
> 
> In this specific case you may be tempted to call the plugin directly, since it supported an `update` argument (for calling `apt-get update`). This is still possible for the plugin in the `stable-2.0` branch, which you should use until munin v3 (`master`) is released.
> I just clarified this detail in the documentation for the plugin in the `master` branch: #1394
> 
> If you want to update the `apt_all` plugin, then I would recommend to install the munin packages in the Debian backports repository for Buster. They are based on the `stable-2.0` branch.

You're right! I was using the old "cronjob" update way with the new "cronjob-less" plugin.
Thank you for this clarification.

And I didn't even remind to use `munin-run`. Shame on me for that. ;)
