### ISSUE TITLE
resizing rrd

### ISSUE THREAD

**Issue by BETLOG** [munin-monitoring/munin#1598]
The default 400 days isn't enough. Given how much wiggly line I can store per MB I'd like to be able to set a significantly higher number; 5 or 10 years, or more.

Is each database created as it's full size? ie: filesize doesnt grow as it fills over time?

How do i resize my existing rrd files?

What are the forseeable problems  with large logs? How large to other people have, in terms of both collective filesizes, and time span.

**Comment by niclan** [comment]
This is documented: https://github.com/munin-monitoring/munin/blob/master/doc/advanced/custom-rrd-sizing.rst

Can't really resize existing rrd files though: The simplest way to get the longer retention is to change the config and then delete the files you want to have long retention, because they will not be remade or resized automatically.

If you want to retain the data you need to use rrd commands to copy the data from the old small file to the new large file. I've never been motivated enough to go through with this myself.
