### ISSUE TITLE
no /var/www/html/munin after installing munin epel rpm packages on rhel9 ?

### ISSUE THREAD

**Issue by vercetty92360** [munin-monitoring/munin#1604]
# Describe the bug

A http interface is not reachable after installing these package on rhel9.3:
munin-common-2.0.75-1.el9.noarch
munin-node-2.0.75-1.el9.noarch
munin-apache-2.0.75-1.el9.noarch
munin-2.0.75-1.el9.noarch

packages are coming from epel repository. erro on browser is "Forbidden. You don't have permission to access this resource."

in /var/log/httpd/error_log, I cna see:

`[Thu Dec 21 11:12:27.375727 2023] [autoindex:error] [pid 56976:tid 57116] [client 10.123.33.20:60058] AH01276: Cannot serve directory /var/www/html/munin/: No matching DirectoryIndex (index.html) found, and server-generated directory index forbidden by Options directive`

and indeed the index.htlm is missing :

```
# ls /var/www/html/munin/
cgi
```

while on rhel8, when we were installing the exact same list of package, the content was:

```
cgi
disk-day.html
disk-month.html
disk-week.html
disk-year.html
index.html
localhost
mail-day.html
mail-month.html
mail-week.html
mail-year.html
network-day.html
network-month.html
network-week.html
network-year.html
problems.html
processes-day.html
processes-month.html
processes-week.html
processes-year.html
sensors-day.html
sensors-month.html
sensors-week.html
sensors-year.html
static
system-day.html
system-month.html
system-week.html
system-year.html
```

# To Reproduce

install the 4 above packages, and browse to http://<you_server>/munin

# Expected behavior

http page reachable

thx a lot!

**Comment by vercetty92360** [comment]
HI team, any update on this?

thx

**Comment by penguinpee** [comment]
You reported an issue which appears to be specific to the EPEL9 package. That is not maintained upstream, but [downstream](https://src.fedoraproject.org/rpms/munin). Issues with distro specific packages should be reported in the distro's [bug tracker](https://bugzilla.redhat.com/enter_bug.cgi?component=munin&product=Fedora%20EPEL&version=3). If you are unsure, report it in the distro's bug tracker first. If the package maintainer determines the issue to be in the code, it can still be reported upstream, while tracking the issue in the distro at the same time.

I'm a Fedora/EPEL package maintainer myself, but not involved with the Munin package in Fedora/EPEL. Sorry for missing your initial report[^1]. Otherwise I would have responded sooner.

[^1]: I was bitten by a nasty bug around that time when attempting to upgrade my system.

**Comment by kimheino** [comment]
See `/usr/share/doc/munin-common/httpd_cgi_graphs.conf` (or `httpd_cron_graphs.conf`) how to configure Apache httpd.

I'm Munin's EPEL maintainer. Please use Redhat Bugzilla for EPEL specific problems. This bug should be closed, it's just missing apache configuration.
