### ISSUE TITLE
issue when installing munin-node on RHEL4

### ISSUE THREAD

**Issue by ttinvent** [munin-monitoring/munin#380]
Hi,

I'm installing munin-node on RHEL4 and having this error when installing perl-Net-SNMP dependencies: 
 #rpm -ivh munin-node-1.2.6-4.el4.noarch.rpm
warning: munin-node-1.2.6-4.el4.noarch.rpm: V3 DSA signature: NOKEY, key ID 217521f6
error: Failed dependencies:
        perl(Net::SNMP) is needed by munin-node-1.2.6-4.el4.noarch

# rpm -ivh perl-Net-SNMP-5.2.0-1.2.el4.rf.noarch.rpm
warning: perl-Net-SNMP-5.2.0-1.2.el4.rf.noarch.rpm: V3 DSA signature: NOKEY, key ID 6b8d79e6
error: Failed dependencies:
        perl(Digest::HMAC) is needed by perl-Net-SNMP-5.2.0-1.2.el4.rf.noarch

# rpm -ivh perl-Digest-HMAC-1.01-13.noarch.rpm
warning: perl-Digest-HMAC-1.01-13.noarch.rpm: V3 DSA signature: NOKEY, key ID e01260f1
error: Failed dependencies:
        perl-Digest-MD5 is needed by perl-Digest-HMAC-1.01-13.noarch

#rpm -ivh perl-Digest-MD5-2.39-1.el4.rf.i386.rpm
warning: perl-Digest-MD5-2.39-1.el4.rf.i386.rpm: V3 DSA signature: NOKEY, key ID 6b8d79e6
Preparing...                ########################################### [100%]
        file /usr/share/man/man3/Digest::MD5.3pm.gz from install of perl-Digest-MD5-2.39-1.el4.rf conflicts with file from package perl-5.8.5-12.1

I found solution using CPAN but didn't success because of internet issue.
So could you help please!

Thanks in advance!

**Comment by ssm** [comment]
RHEL4 is ten years old, and Red Hat ended support three years ago, and the Munin 1.2.6 is seven years old.  Much has changed since that.

You may need to look for the perl module releases from around that time to avoid the conflicts RPM reports.

**Comment by niclan** [comment]
You can install the extra packages with yum, no need for cpan madness.

Nicolai
--
Nicolai Langfeldt, OSS Arkitekt
Broad|Net - Fiber - the business revolution
________________________________
Fra: ttinvent [notifications@github.com]
Sendt: 27. mars 2015 07:25
Til: munin-monitoring/munin
Emne: [munin] issue when installing munin-node on RHEL4 (#380)


Hi,

I'm installing munin-node on RHEL4 and having this error when installing perl-Net-SNMP dependencies:
#rpm -ivh munin-node-1.2.6-4.el4.noarch.rpm
warning: munin-node-1.2.6-4.el4.noarch.rpm: V3 DSA signature: NOKEY, key ID 217521f6
error: Failed dependencies:
perl(Net::SNMP) is needed by munin-node-1.2.6-4.el4.noarch

rpm -ivh perl-Net-SNMP-5.2.0-1.2.el4.rf.noarch.rpm

warning: perl-Net-SNMP-5.2.0-1.2.el4.rf.noarch.rpm: V3 DSA signature: NOKEY, key ID 6b8d79e6
error: Failed dependencies:
perl(Digest::HMAC) is needed by perl-Net-SNMP-5.2.0-1.2.el4.rf.noarch

rpm -ivh perl-Digest-HMAC-1.01-13.noarch.rpm

warning: perl-Digest-HMAC-1.01-13.noarch.rpm: V3 DSA signature: NOKEY, key ID e01260f1
error: Failed dependencies:
perl-Digest-MD5 is needed by perl-Digest-HMAC-1.01-13.noarch

#rpm -ivh perl-Digest-MD5-2.39-1.el4.rf.i386.rpm
warning: perl-Digest-MD5-2.39-1.el4.rf.i386.rpm: V3 DSA signature: NOKEY, key ID 6b8d79e6
Preparing... ########################################### [100%]
file /usr/share/man/man3/Digest::MD5.3pm.gz from install of perl-Digest-MD5-2.39-1.el4.rf conflicts with file from package perl-5.8.5-12.1

I found solution using CPAN but didn't success because of internet issue.
So could you help please!

Thanks in advance!
