### ISSUE TITLE
Empty nodes show up as "domain" in data given to the template

### ISSUE THREAD

**Issue by ssm** [munin-monitoring/munin#413]
When a node is defined, but has no data yet, the data passed to the template indicates the host is a "domain" and not a "host".

This was visible after defining a node in munin.conf, but where the munin node did not allow this master to connect.

See also #411

**Comment by chteuchteu** [comment]
I just investigated, and discovered that in the [munin-overview template](https://github.com/munin-monitoring/munin/blob/devel/web/templates/munin-overview.tmpl#L40), it seems that those faulty nodes are seen as domains because they don't have any categories: `<TMPL_IF NAME="NCATEGORIES"><span class="host"><TMPL_ELSE><span class="domain"></TMPL_IF>`

Is there a reason for this? If not, I can delete this condition and force the `<span class="host">`.

**Comment by chteuchteu** [comment]
Alright, I actually think that's because of possibly nested groups (see the multiple nested GROUPS loops)
