### ISSUE TITLE
Allow domain/host names

### ISSUE THREAD

**Issue by idenkov** [munin-monitoring/munin#504]
This is not a bug, more like a feature request, but will be nice to have option to allow domain name on the node.

**Comment by ssm** [comment]
Judging from the Net::Server perl module documentation, this should work 

See  http://search.cpan.org/~rhandom/Net-Server-2.008/lib/Net/Server.pod#CONFIGURATION_FILE

**Comment by oscarmlage** [comment]
I think it's not working (yet). I've been taking a look to [this](https://metacpan.org/pod/release/RHANDOM/Net-Server-2.008/lib/Net/Server.pod#CONFIGURATION-FILE) and it seems that in `Net::Server` you can enable the `reverse_lookups` and then you can add something like `allow domain\.com`. I've tried and it's not working (`munin-node 2.0.6-4+deb7u4`).

   reverse_lookups on
   allow domain\\.com

I've tried `reverse_lookups on` and `reverse_lookups 1` but I was no lucky. Any other hint I'm missing?. In the end I've made the connection via tunnel ssh and autossh but it would be nice to add this feature to munin because it seems to be supported in `Net::Server` perl module by default.

**Comment by sumpfralle** [comment]
Just wild guessing: please check whether it works, after you add `reverse_lookups` to `%handled_by_net_server` in `Munin/Node/Config.pm`.

**Comment by oscarmlage** [comment]
@sumpfralle I've added the option as you said, the file `/usr/share/perl5/Munin/Node/Config.pm` has now the `reverse_lookups` there:

     my %handled_by_net_server = map { $_ => 1 } qw(
           allow
           deny
           cidr_allow
           cidr_deny
           reverse_lookups
      );

Then I've restarted the munin-node and tried to connect from my `domain.com` machine but got same result (`REMOTEIP` is the ip of the munin-server, `LOCALIP` is the ip of the munin-node):

    2019/01/08-10:38:53 CONNECT TCP Peer: "[::ffff:REMOTEIP]:43797" Local: "[::ffff:LOCALIP]:4949"
    2019/01/08-10:38:53 [13134] Denying connection from: ::ffff:ffff:REMOTEIP

Tried with both `reverse_lookups on` and `reverse_lookups 1` but no lucky.

- OS: Debian 9.6
- Munin Node Version: v2.0.33-1
- Debian package: munin-node-2.0.33-1

**Comment by sumpfralle** [comment]
Are you sure, that the reverse DNS resolution for IPv4 or IPv6 (check which is really used) works on the target host?

**Comment by oscarmlage** [comment]
I think so, `dig -x LOCALIP` in the target host gives me the same PTR record than the one I've added to the `allow` entry in the `munin-node.conf`.

**Comment by sumpfralle** [comment]
See #1175 for a follow-up on this issue.
