### ISSUE TITLE
Generating json from munin

### ISSUE THREAD

**Issue by sh3llsh0ck** [munin-monitoring/munin#505]
Hello,
my current master munin: ```This is munin-node v2.0.25```
I found nothing in documentation about this so i need to know where to generate json
thanks

**Comment by chteuchteu** [comment]
You can get JSON data from plugins by replacing the `.png` extension of any graph with `.json`:

    .../apache_accesses-day.png

becomes

    .../apache_accesses-day.json

**Comment by sh3llsh0ck** [comment]
Hello @chteuchteu ,

lets say i have a working URL similar to the following:

```
http://my_munin_server/munin/group_name/node_name/uptime-day.png
```
in the server i dont have uptime-day.json , so i won't be able to view it , Am i missing any configuration ?

Thanks

**Comment by chteuchteu** [comment]
If I'm not mistaken, you have to use `munin-cgi` in order to make it work since it is dynamically generated.

Once enabled, you'll be able to browse munin result pages using `4948` port (by default).
Please note that it also work with `.xml` and `.svg` extensions.

Here's an example with `demo.munin-monitoring.org`:

- http://demo.munin-monitoring.org/munin-cgi/munin-cgi-graph/munin-monitoring.org/demo.munin-monitoring.org/if1sec_eth0-day.png
- http://demo.munin-monitoring.org/munin-cgi/munin-cgi-graph/munin-monitoring.org/demo.munin-monitoring.org/if1sec_eth0-day.svg
- http://demo.munin-monitoring.org/munin-cgi/munin-cgi-graph/munin-monitoring.org/demo.munin-monitoring.org/if1sec_eth0-day.xml
- http://demo.munin-monitoring.org/munin-cgi/munin-cgi-graph/munin-monitoring.org/demo.munin-monitoring.org/if1sec_eth0-day.json

**Comment by sh3llsh0ck** [comment]
Thanks for the followup, In order to have a url like what you mentioned should i follow this http://munin-monitoring.org/wiki/MuninConfigurationMasterCGI ? or something else ?

**Comment by ssm** [comment]
For this feature, you need munin 2.1
