### ISSUE TITLE
Line 201 of mysql_innodb causes problems with MariaDB 10.0 or newer

### ISSUE THREAD

**Issue by HSorgYves** [munin-monitoring/munin#507]
Line 201 of mysql_innodb is:
if [ "$ver" ">" "5.0" ]; then
As the version number in MariaDB is exceeding 1 digit, this line no longer works fine. I suggest to change it to:
if [ "${ver%.*}" -ge "5" ]; then

**Comment by grooverdan** [comment]
The mysql_bytes, mysql_innodb, mysql_isam_space, mysql_queries, mysql_slowqueries, mysql_threads have effectively had no maintenance.

Rather than putting too much effort in there is worth purging them? Is there actually anything of use there that isn't in mysql_?

suggesting turning off innodb_file_per_table in mysql_innodb for space calculations seems a bit wrong, (makes it harder to manage space so you can monitor it better).

mysql_isam_space doesn't seem particularly useful (to me anyway)

**Comment by sumpfralle** [comment]
> Rather than putting too much effort in there is worth purging them?

Indeed!
They were declared obsolete in 2009 (see 18cefb93a0a0fd28b084045e067f779286bfb73a). Now I removed them.
