### ISSUE TITLE
graph images not showing after installation

### ISSUE THREAD

**Issue by sh3llsh0ck** [munin-monitoring/munin#515]
Images is not shown , what should i do ? there is no connection issue between node and master as it was working before with munin 2.0 on master. and i can telnet too

![screenshot from 2015-07-10 19 58 38](https://cloud.githubusercontent.com/assets/4104127/8625582/65888838-2748-11e5-9b8a-f1c0ef709230.png)

**Comment by ssm** [comment]
Start by looking at the logs.  It could be anything, really.

**Comment by naught101** [comment]
I am seeing a similar problem, with munin running via fascgi and nginx. I followed the directions in http://guide.munin-monitoring.org/en/stable-2.0/example/webserver/nginx.html#webserver-configuration .

I can see the HTML and static content fine, and I can see the zoomable graphs fine. I can't see the thumbnail images. 

The images DO appear to be being generated correctly, e.g.
```
file  /var/cache/munin/www/localdomain/localhost.localdomain/cpu-day.png
/var/cache/munin/www/localdomain/localhost.localdomain/cpu-day.png: PNG image data, 497 x 371, 8-bit/color RGB, non-interlaced
```
They just don't show. 

I've looked in all the logs, and can't see any errors or warnings that seem relevant. 
```
/var/log/munin/munin-cgi-graph.log  /var/log/munin/munin-html.log            /var/log/munin/munin-node.log
/var/log/munin/munin-cgi-html.log   /var/log/munin/munin-limits.log          /var/log/munin/munin-update.log
/var/log/munin/munin-graph.log      /var/log/munin/munin-node-configure.log
```

if I use right click one of the missing images, and copy the image url and paste it into the address bar, I get taken to the page that the image links to, instead of the image itself. I'm guessing that this means that something in the nginx rewrite rules or the fastcgi scripts is wrong? But I can't tell what should be serving the images, nginx directly, or the /usr/lib/munin/cgi/munin-cgi-html script (guessing the latter, but the perl is a bit indecipherable to me).

**Comment by sumpfralle** [comment]
@mostafahussein: thank you for your input, but I guess, this is a different issue.

Please open a new issue and attach:
* your nginx configuration
* the raw html website that fails to display the images
* related log messages from nginx's error log (if any)

Thank you!

**Comment by naught101** [comment]
Finally got back to this. Was a problem with my nginx config - I'd messed it up. I followed the instructions here and it worked:
https://uname.pingveno.net/blog/index.php/post/2013/08/25/Configure-Munin-graphs-with-Nginx-and-Debian-7

**Comment by sumpfralle** [comment]
Thanks for your clarification!
