### ISSUE TITLE
Munin didn`t generate html pages using cgi

### ISSUE THREAD

**Issue by novashdima** [munin-monitoring/munin#525]
Hello.
Before I am used graphs and html generation by cron, but this creates big load of processor.
So i changed generarion of graphs to cgi, all right.
But html pages didn`t generated.
Munin 2.0.25. 3 servers with Debian and Ubuntu.

Apache 2.22 and 2.4.
Apache 2.22 config:
http://pastebin.com/s8JkeYU7

Munin conf:
http://pastebin.com/K6LfGqwY

tail -n 20 /var/log/apache2/error.log
http://pastebin.com/wjNtwdQ2

/var/log/munin/munin-cgi-graph.log is empty
/var/log/munin/munin-cgi-html.log:
2015/07/14 23:44:03 [PERL WARNING] Use of uninitialized value in split at /usr/lib/munin/cgi/munin-cgi-html line 60.
2015/07/28 15:50:29 [PERL WARNING] Use of uninitialized value in split at /usr/lib/munin/cgi/munin-cgi-html line 60.

**Comment by kenyon** [comment]
Did you get this working? If not, ask for help in our IRC channel #munin on irc.oftc.net. Thanks.

**Comment by zystem** [comment]
same problem on CentOS
2021/06/03 16:59:34 [PERL WARNING] Use of uninitialized value in split at /var/www/html/munin/cgi/munin-cgi-html line 60.
Munin version 2.0.66

**Comment by sumpfralle** [comment]
According to the source, this is caused by the lack of the `PATH_INFO` environment variable.
I guess, your webserver configuration needs a change?
(you should probably report this to the maintainer of your distribution's munin package, if the webserver configuration is part of that package)

**Comment by doublehp** [comment]
I was having the same issue (broken page + message in apache2/error.log) ... but, only when requesting http://server/munin instead of http://server/munin/ . My fix was to add this section in the middle of /etc/apache2/conf-enabled/apache24.cgi.munin.conf ( aka /etc/munin/apache24.cgi.conf )

<Location /munin>
    RewriteEngine On
    RewriteCond %{REQUEST_URI} ^/munin$
    RewriteRule ^(.*)$ /munin/ [R=301,L]
</Location>

Then
a2enmod rewrite
service apache2 restart

Obviously, only the welcome page is broken (it also breaks the child links, that was the tip for me: child plugins pages were in http://server/ instead of http://server/munin/ )

=> I am not sure it's a distribution issue.

Debian xenial
Munin 2.0.25
