### ISSUE TITLE
Host disappears from Munin::Overview index.html in case of failed connection to host

### ISSUE THREAD

**Issue by myroslav** [munin-monitoring/munin#579]
This is essentially reopening of http://munin-monitoring.org/ticket/758.

> I just noticed, that if a host which is monitored fine by munin master, stops responding (for example, munin-node is down, or no route to host), it disappears from the Munin::Overview html page.

This is still happening with 2.0.4 and 2.1.2

**Comment by ssm** [comment]
The "munin-update" process creates its state file each run.  This state file is used by other parts of munin, for instance to generate html.

This is also visible if you run "munin-update --host something.example.com", as everything else will disappear from the overview until munin-update has run again.

**Comment by mrch25** [comment]
I have the same issue in:
* Munin 2.0.19-3
* Ubuntu 14.04.2 LTS

**Comment by ssm** [comment]
This affects all known versions of munin, until munin-update is rewritten to use a persistent database.

**Comment by ssm** [comment]
Related feature request: #720

**Comment by sumpfralle** [comment]
[niclan commented](https://github.com/munin-monitoring/munin/issues/1091#issuecomment-424438354) in a duplicate issue (#1091):

> In 2.0 there used to be some code to copy out enough of the data tree to preserve the html so the graphs would be viewed even if the node went temporarily offline. I think this code was supposed to keep the node in the html indefinitely - as long as the node is configured. But even in 2.0 I saw that nodes dropped out while still configured - but I never delved into why.

**Comment by sumpfralle** [comment]
I think, I found a (or maybe *the*) cause for such losses of previous history.

Consider the following scenario:
1. A plugin breaks somehow and emits trash to its stdout.
2. The malformed content [causes a warning but is stored anyway in the datafile](https://github.com/munin-monitoring/munin/blob/stable-2.0/master/lib/Munin/Master/Utils.pm#L689). This tolerance may be a sane approach, in order to support future changes. I cannot judge.
3. When the `datafile` is parsed, any parsing error (e.g. for the malformed line above) is allowed to rise through the caller chain up to file parsing itself (e.g. see [`_parse_config_line` tolerating a failure](https://github.com/munin-monitoring/munin/blob/stable-2.0/master/lib/Munin/Master/Config.pm#L475)).

Thus a single malformed line in `datafile` breaks its parsing. Thus old config data is always lost in the next run. This causes nodes to disappear immediately from the HTML representation.

I am working on a fix.

**Comment by sumpfralle** [comment]
A small addition to my previous description:
* only hosts following the *first* error in the `datafile` are ignored (this probably causes a bit of perceived randomness)

The fix is applied now and will be part of the next release.

**Comment by sumpfralle** [comment]
For the recording: relased in 2.0.48.
