### ISSUE TITLE
Please set sensible file-permissions (don't rely on umask)

### ISSUE THREAD

**Issue by madduck** [munin-monitoring/munin#620]
At least `munin-html` uses `umask` to determine the permission on files it generates. As I have `umask` set at `077` (of course, for shell sessions), this means running things manually yields unreadable HTML files.

**Comment by sumpfralle** [comment]
Currently there is no configuration setting for file permissions created by munin.

Thus I think, there could be three approaches:
1. allow `umask` to influence munin's operation (this is the current situation)
2. ignore `umask` and use a hardcoded `644` permission for all generated files
3. add a configuration setting for the wanted permissions of new files (ignoring `umask`)

I think, your request points at (2).
I would try to avoid (3), since I do not consider it to be worth the effort.
I would slightly prefer (1) over (2), since it allows configuration. But I do not really have an opinion.

Thus I am tempted to dismiss this feature request.
But if you think, that (2) would be preferable, a single sentence of reasoning would surely convince me.

**Comment by madduck** [comment]
I think the easiest fix would be to to set umask early on in the script for `munin-html`, or a wrapper script, to 022, because I see no reason why the permissions on HTML files should be any different.

Alternatively, maybe a warning could be issued if `umask 077` is encountered.

Anyway, thanks for taking your time to think about this. If you prefer to dismiss, then that's okay. You are the authority here. ;)

**Comment by sumpfralle** [comment]
> Anyway, thanks for taking your time to think about this. If you prefer to dismiss, then that's okay. You are the authority here. ;)

After letting this issue rest for way too long, I humbly accept your offer and close this issue.

I think, it is reasonable to respect the caller's `umask` setting. Additionally I would really like to avoid cluttering munin's configuration even more. Thank you for your thoughts, your patience and your understanding.
