### ISSUE TITLE
Help needed: compose url to graph using contact script

### ISSUE THREAD

**Issue by hugochinchilla** [munin-monitoring/munin#659]
I'm trying to edit this script to  get notifications on a slack channel which would include a link to the graph image, so it can be analyzed without entering the munin dashboard.

Can someone give me some advice on how to get the graph url using the data available for contact scripts?

**Comment by chteuchteu** [comment]
I don't think there is currently a proper way of doing this. You could build the graph URL using the following information:

- munin base URL (`http://demo.munin-monitoring.org/`)
- group: `${var:group}` (`munin-monitoring.org`)
- host: `${var:host}` (`demo.munin-monitoring.org`)

Unfortunately, we don't have access to the plugin name. All we have about it is the `${var:graph_title}` - "Interface 1sec stats for eth0" instead of "if1sec_eth0" (or at least it is not [documented](http://guide.munin-monitoring.org/en/latest/tutorial/alert.html#munin-alert-variables))

This will at least help you build this part of the URL: 

    http://demo.munin-monitoring.org/munin-monitoring.org/demo.munin-monitoring.org/[plugin-name]-day.png
            [munin base URL]        /    ${var:group}    /       ${var:host}       /[plugin-name]-day.png

Warning: this would not work with multigraph plugins because of the subdirectory in their URL

You can read more about alerts in the [Munin Guide](http://guide.munin-monitoring.org/en/latest/tutorial/alert.html)

**Comment by hugochinchilla** [comment]
Thanks @chteuchteu, the problem you mention is what I feared when I read the docs, I hoped someone here would know about some variable not documented which I could use to extract the plugin name.

How about creating a new issue to have the plugin name included in future releases?

**Comment by chteuchteu** [comment]
Yep that would indeed be legit!
I quickly looked into munin's code but didn't found where those variable gets populated so it's possible that it's already here but not documented.

Yes please create a new issue or pull request about this!

I'm closing this issue but don't hesitate to reopen it if you think that your problem isn't solved.
