### ISSUE TITLE
Notes on installing on RHEL6 w/ fixes

### ISSUE THREAD

**Issue by SkyMoCo** [munin-monitoring/munin#699]
I installed munin-2.0.25-11.el6.noarch.rpm on my RHEL6 machine and ran into some minor issues, included is what did to fix it.

The first was that graphs do not generate as the rrdtool I installed (rrdtool-1.4.7-1) doesn't support the "-border" option.   I commented that out of GraphOld.pm.

Second was that munin-stats did not run after the logs were rolled each night, fixed that by creating a munin-stats plugin config file and had it run as the munin user.

**Comment by sumpfralle** [comment]
Hello SkyMoCo,

thank you for reporting these problems.

Both issues are usually fixed by package maintainers (here: RHEL). They adapt the source release to the specific details of the distribution.
Feel free to leave a link to the corresponding issue in your distribution here in this ticket. Maybe someone can help the package maintainer with details.

Cheers,
Lars
