### ISSUE TITLE
mariadb queries error

### ISSUE THREAD

**Issue by paolobenve** [munin-monitoring/munin#735]
As explained in https://mariadb.com/kb/en/mariadb/server-status-variables/#com_select, since mariadb 5.5 the Com_select status variable include chache_hits

The mysql plugin erroneously uses Com_select variable to get select values, while it should use Com_select - cache_hits

**Comment by sumpfralle** [comment]
Thank you for pointing out this change!

Indeed the situations seems to be the following:
* before v5.5: `Com_select` counts only the number of executed `SELECT` queries (without counting the queries that were served from the cache)
* since v5.5: `Com_select` counts all `SELECT` queries. A part of these queries may have been served from the cache.

I *think* the new approach of mariadb is the behaviour that can be intuitively expected from a command counter for `SELECT`. Thus I tend to just keep the current approach of counting.

But I understand, that this can result in a change of the numbers, that are displayed by the munin plugin. Thus keeping the old interpretation stable (by using `Com_select - Qcache_hits`) is also an option.

In this case I strongly suggest to just follow the attribute as provided by mariadb, since the changed interpretation of this field happened in 2012. Thus any change in the munin plugin would help only a small minority of people that run an older version of mariadb *now* and that would upgrade to a newer version *after* we change the behaviour of the munin plugin. The relevant version of mariadb (5.3) was EOL in 2017.

Thus closing the issue. Please re-open, if you disagree.
(your report helped me to find a different minor issue of the `mysql_` plugin - thus it was definitely helpful)
