### ISSUE TITLE
Unable to determine eth0 interface speed on KVM guest  with  if_ plugin

### ISSUE THREAD

**Issue by ron-h** [munin-monitoring/munin#771]
Munin version 2.0.28-2 on Centos7.3 (epel) gives an error in munin-node.log:
Error output from if_eth0:
2017/01/02-17:15:11 [29248] 	/etc/munin/plugins/if_eth0: line 94: [: : integer expression expected
Munin version 2.0.25-11 on Centos7.2  did not log this error because of conditional check construction.

**Comment by kenyon** [comment]
What is the value of /sys/class/net/eth0/speed?

**Comment by kenyon** [comment]
Thanks for the report. I'm guessing your value of `/sys/class/net/eth0/speed` is empty.

This should be fixed in our code now. To fix your node, you'll want to specify the interface speed manually.

On a KVM guest, there is no way to determine the interface speed, as far as I know. So the plugin allows you to specify the speed using an environment variable ([see the plugin documentation](https://github.com/munin-monitoring/munin/blob/master/plugins/node.d.linux/if_#L20)) probably from `/etc/munin/plugin-conf.d/munin-node` on the node (that's where plugin configuration is done on Debian, it may be different on CentOS).

**Comment by ron-h** [comment]
Thanks Kenyon. Value is not an integer.
cat: /sys/class/net/eth0/speed: Invalid argument
I will set the speed manually
