### ISSUE TITLE
Groups structure rrd files Uncomfortable

### ISSUE THREAD

**Issue by tebaly** [munin-monitoring/munin#840]
if _no group_, file structure

#/var/lib/munin
```
    /node-name/node-name-plugin-data.rrd
```
If _group name_ "any-group", file structure

#/var/lib/munin
```
    /any-group/node-name-plugin-data.rrd
```

Any simple way to rename node (and save old data)
* from no group to _group name_ and new _node name_?
* from group name and node name to _new node_ name _without group_?

It is not simple! That's just terrible :cry:

---

## Why not  
1. Wthout suffix **node-name-**
#/var/lib/munin
```
    /node-name/plugin-data.rrd
```

2. Group name as **subfolder** and _no suffix_ in RRD files
#/var/lib/munin
```
    /any-group/node-name/plugin-data.rrd 
```

Then rename simple as copy files from folder to folder.

**Comment by sumpfralle** [comment]
I am not sure that I understand what you want to achieve.
Which problem would you like to solve?

**Comment by tebaly** [comment]
When you already have a list of servers. When you have statistics data. When your servers are named in groups. And you need to rename one of the servers and save the statistics data. **How will you do this?**
* _web.hosts_ - is a group name
* _test.194_ - is a node nsme
* In this group _there is still_ - prod.200 and dev.100 and etc
* Each server has **360 statistics files**

![image](https://user-images.githubusercontent.com/9466814/27214641-38044590-5276-11e7-9f7b-be72d6f2e511.png)

How do you rename a single server*?
How do you rename more than one server*?

---

I suggest not specifying the server name in each statistics file. I propose to make a subdirectory in the group with the server name and in the file names remove it. Like /any-group/**node-name**/plugin-data.rrd

Then to rename one server you will need to rename only the directory.

PS: When there is no group: /**node-name**/**node-name**-plugin-data.rrd (Each server has **360 statistics files**) I have 21 servers and each has 360 files - total 7560 files need to rename

**Comment by sumpfralle** [comment]
Thank you - I think, now I understand your goal.

But as far as I can estimate the related required changes, I do not think, that this change is going to happen, since:
* the munin code requires changes
* 3rd party tools that rely on this directory layout require changes
* package maintainers of all distributions (e.g. the Debian maintainer of the munin package) would need to write migration scripts for changing the current local directory structure (this is really a pain to do correctly)

Thus while I understand your approach, I do not think, that the ease of renaming a host (and keeping its data files) outweighs the above amount of required work to make this happen.
Or do I misunderstand you?

How about using simple shell expressions for renaming the data files?
```
# move host to a different group
find /var/lib/munin/group-foo/ -type f -name "host-bar-*" | while read fname; do mv "$fname" "/var/lib/munin/group-baz/$(basename "$fname")"; done
# rename host in group
find /var/lib/munin/group-foo/ -type f -name "host-bar-*" | while read fname; do mv "$fname" "$(dirname "$fname")/$(basename "$fname" | sed 's/^host-bar-/host-baz-/')"; done
```
(not tested)

**Comment by tebaly** [comment]
I decided this for myself. This is not a question, but a proposal :)

**Comment by sumpfralle** [comment]
I am cleaning up a bit.
Regarding the implementation of this proposal: I do not think, that the benefits outweigh the effort. Thus I am closing this proposal.
