### ISSUE TITLE
AMD GPU monitoring with recent drivers

### ISSUE THREAD

**Issue by akosmaroy** [munin-monitoring/munin#854]
I wonder if there is a solution to monitor AMD GPUs with recent drivers on Linux.
the new AMD drivers no longer include the aticonfig utility, but expose the details of the cards via the /sys interface. for example:

```
# cat /sys/class/drm/card1/device/hwmon/hwmon0/temp1_input 
46000
```

would mean 46°C

etc.

also read more at http://forum.ethereum.org/discussion/comment/62745

**Comment by sumpfralle** [comment]
In case that the AMD driver also populates the virtual directories `/sys/class/hwmon/hwmon*`, then you may just use the [hwmon plugin](https://github.com/munin-monitoring/contrib/blob/master/plugins/sensors/hwmon).

If the driver decides to differ, then you could make the base directory of the above plugin configurable, in order to make it work with that driver, too. (given that the ADM driver provides the same data structure as other hwmon sensors)

**Comment by niclan** [comment]
@akosmaroy : asking for plugins is better on the munin-users list or irc. The fix you require is probably quite simple but requires both hardware and the right programming skill. Closing.
