### ISSUE TITLE
varnish plugin broken with recent varnish versions

### ISSUE THREAD

**Issue by fgsch** [munin-monitoring/munin#864]
As per https://github.com/varnishcache/varnish-cache/issues/2377, recent changes to varnishstat have broken the plugin.

**Comment by sumpfralle** [comment]
The following lines in the `varnish_` plugin should require a change:
```perl
        my $name = $state{'values'}{'name'};
        my $type = $state{'values'}{'type'};
```

The new approach should be like this:
* if `name` contains a dot, then (I can only spell this in python):
    ```python
    type, name = name.split(".", 1)
    ```
* otherwise: read `type` from the `state` (as the original code did it)

Would someone like to translate this into beautiful perl?

**Comment by sumpfralle** [comment]
I implemented the above procedure.

@fgsch: would you please test the new version of the plugin from my branch before I merge it?
* the patch/commit:
  https://github.com/sumpfralle/munin/commit/7f29ef450ba68f1873b6bdbec4b19c38bd946f0d
* the full plugin (just replace the shebang):
  https://github.com/sumpfralle/munin/blob/varnish-864/plugins/node.d/varnish_.in

**Comment by fgsch** [comment]
@sumpfralle I don't use this plugin. I was merely reporting the issue, sorry.

**Comment by sumpfralle** [comment]
OK - thanks.
According to the change specification of varnish, it should work.
