### ISSUE TITLE
Munin not showing graph webpage

### ISSUE THREAD

**Issue by spanishearl** [munin-monitoring/munin#872]
I am building a new munin server, and I moved our plugins over from the existing server to the new one, and created the symlinks for it. Everythinhg appears to be working, however when going to the address for the new munin sever, I get the default Debian Apache webpage "It works".

I've tried commenting out the line "_Require local_ and add _Require all granted_ and _Options FollowSymLinks SymLinksIfOwnerMatch_ as per https://www.howtoforge.com/tutorial/server-monitoring-with-munin-and-monit-on-debian/

However, that kills the "It works" page and gives me a "Can't reach page" error instead. 

The syslinks exist, but still show as off when I use the --suggest command. 

I have gone through the installation and configuration as per the Munin tutorials, and still cannot seem to get it up and running. Is there any other suggestions, or perhaps a few links to options I can try to figure out what I may be missing.

I'm brand new to munin, and intermediate to Linux.

**Comment by sumpfralle** [comment]
The problems you are encountering seem to be specific to the configuration of your webserver - and not specific to munin.

Which distribution do you use? Did you install munin from their package repositories? Which version of munin is installed?

Wild guessing: the default setup on Debian (and probably most other distributions) publishes munin-related content below /munin. Thus you should try http://localhost/munin instead of http://localhost/.
btw.: this is mentioned in the second paragraph of /usr/share/doc/munin/README.Debian.

Usually it is a good approach to look for the documentation of a package within your distribution before looking somewhere else for general-purpose tutorials.

Good luck!

**Comment by sumpfralle** [comment]
I assume, this is an individual configuration issue. Closing.
