### ISSUE TITLE
Munin data updating intermittently 

### ISSUE THREAD

**Issue by arvindkrishnaa1988** [munin-monitoring/munin#890]
Hi,

We noticed Munin data is not updating continuously and it is intermittent. Upon checking logs, could see 'returned no data for label'. Can you help us in fixing the issue to get the full data.

Thanks in advance.

**Comment by sumpfralle** [comment]
It looks like one plugin fails to output the `value` attribute for a field. Usually this is a problem of the plugin implementation.

You should do the following:
* verify the config output of the plugin (e.g. `munin-run PLUGIN_NAME config`)
* verify the data output of the plugin (e.g. `munin-run PLUGIN_NAME`)

Do you see missing fields in the data output?

Is this a plugin that is maintained by the munin people (here in the munin or in the munin-contrib repositories)?

Otherwise you are on your own :(
(Feel free to discuss potential issues with your plugin on our IRC channel - `#munin` at irc.oftc.net)

**Comment by niclan** [comment]
@arvindkrishnaa1988 : This is better to take to the mailing list or irc channel.
